source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!


target 'MHZakerShop' do

#富文本
pod 'YYText', '~> 1.0.5'

#AutoLayout
pod 'Masonry', '~> 1.0.1'

#缓存tableViewCell的高度
pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'

#网络请求
pod 'AFNetworking', '~> 3.1.0'

#图片缓存
pod 'SDWebImage', '~> 3.8.1'

#刷新控件
pod 'MJRefresh', '~> 3.1.12'

#字典转模型
pod 'MJExtension', '~> 3.0.13'

#颜色分类
pod 'Colours', '~> 5.13.0'

#滚动视图
pod 'MHCycleScrollView', '~> 1.0.0'

#根据颜色 生成一张图片
pod 'UIImage+ImageWithColor', '~> 1.3'

end
